"""profile lastname_name -> last_name

Revision ID: 94682a8d6561
Revises: 5dfe441b41ca
Create Date: 2025-08-28 11:25:46.418502

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "94682a8d6561"
down_revision: Union[str, Sequence[str], None] = "5dfe441b41ca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("last_name", sa.String(length=50), nullable=True))
    op.drop_column("profiles", "lastname_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("profiles", sa.Column("lastname_name", sa.VARCHAR(length=50), nullable=True))
    op.drop_column("profiles", "last_name")
    # ### end Alembic commands ###
